# Generated by Django 4.1 on 2022-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('difficulty', models.CharField(choices=[('easy', 'Eazy'), ('normal', 'Normal'), ('hard', 'Hard'), ('special', 'Special')], default='easy', max_length=50)),
                ('cost', models.PositiveSmallIntegerField(default=0)),
                ('times_completed', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
