# Generated by Django 4.1 on 2022-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_challenge_created_challenge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH'), ('RUB', 'RUB'), ('GBP', 'GBP'), ('PLN', 'PLN'), ('CZK', 'CZK')], default='USD', max_length=50),
        ),
    ]
