# Generated by Django 4.1 on 2022-11-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_challenge_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='currency',
        ),
    ]
