# Generated by Django 4.1 on 2022-11-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task'),
        ),
    ]
