# Generated by Django 4.1 on 2022-11-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task'),
        ),
    ]
