# Generated by Django 4.1 on 2022-10-15 08:30

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.authentication.models.User.get_upload_picture),
        ),
    ]
