# Generated by Django 4.1 on 2022-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('authentication', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed_change',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='solutions',
            field=models.ManyToManyField(blank=True, to='core.challenge'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_earned',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
