# Generated by Django 4.1 on 2022-11-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_email_confirmed_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_earned',
        ),
    ]
